# config/meta.yml
meta_product_name: "Buddy"
meta_title: "Buddy - Simplifying life for you and your pet"
meta_description: "Organize your pet's daily life, health, nutrition and activities, and simplify your own."
